# Site settings
title: El Blog de Make it Real 
email: german.escobar@makeitreal.camp
description: "Especial√≠zate en Desarrollo Web. Avanza tu carrera con un programa estructurado y personalizado"
baseurl: ""
url: "http://blog.makeitreal.camp/"
twitter_username: makeitrealcamp
github_username:  jekyll
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: :title

sass:
    sass_dir: css
    style: compressed

gems:
  - jekyll-redirect-from